import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col min-h-screen bg-custom-gradient">
      <Navbar />
      <main className="flex flex-col items-center justify-center flex-grow">
        <div className="absolute top-4 left-4">
          <Sidebar />
        </div>
        {children}
      </main>
    </div>
  );
}
