/* Lógico_1: */

CREATE TABLE JOGO (
    IDJOGO INT AUTO_INCREMENT PRIMARY KEY,
    RODADA INT,
    TIME_1 VARCHAR(60),
    TIME_2 VARCHAR(60),
    DATA_HORA DATETIME,
    CAMPEONATO VARCHAR(50)
);

CREATE TABLE CANAL (
    IDCANAL INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CANAL VARCHAR(50),
    LOGO_CANAL VARCHAR(255)
);

CREATE TABLE PASSA_EM (
    ID_CANAL INT,
    ID_JOGO INT
);

CREATE TABLE USUARIO (
    IDUSUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60),
    TIME_FAVORITO VARCHAR(30),
    SENHA_HASH VARCHAR(255),
    EMAIL VARCHAR(100),
);

ALTER TABLE PASSA_EM ADD CONSTRAINT FK_PASSA_EM_1
    FOREIGN KEY (ID_JOGO)
    REFERENCES JOGO (IDJOGO)
    ON DELETE SET NULL;

ALTER TABLE PASSA_EM ADD CONSTRAINT FK_PASSA_EM_2
    FOREIGN KEY (ID_CANAL)
    REFERENCES CANAL (IDCANAL)
    ON DELETE SET NULL;